export enum TYPE_KEYS {
  REQUEST_TOKEN_REQUEST = 'films/session/REQUEST_TOKEN_REQUEST',
  REQUEST_TOKEN_SUCCESS = 'films/session/REQUEST_TOKEN_SUCCESS',
  REQUEST_TOKEN_FAILURE = 'films/session/REQUEST_TOKEN_FAILURE',

  SESSION_ID_REQUEST = 'films/session/SESSION_ID_REQUEST',
  SESSION_ID_SUCCESS = 'films/session/SESSION_ID_SUCCESS',
  SESSION_ID_FAILURE = 'films/session/SESSION_ID_FAILURE',
  SET_SESSION_ID = 'films/session/SET_SESSION_ID',

  DELETE_SESSION_REQUEST = 'films/session/REQUEST_DELETE_SESSION',
  DELETE_SESSION_SUCCESS = 'films/session/DELETE_SESSION_SUCCESS',
  DELETE_SESSION_FAILURE = 'films/session/DELETE_SESSION_FAILURE',
}
