import Head from 'next/head';
import { Typography } from 'antd';

const { Title } = Typography;

export default function Home() {
  return (
    <div className={''}>
      <Head>
        <title>Now watching</title>
        <meta name="description" content="Generated by create next app" />
        {/* <link rel="icon" href="/favicon.ico" /> */}
      </Head>

      <Title>Now watching</Title>
    </div>
  );
}
