import Head from 'next/head';
import { Typography } from 'antd';
import { ROUTES } from '../src/common/constants';

const { Title } = Typography;

export default function Popular() {
  const pageName = ROUTES.POPULAR.NAME;

  return (
    <>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Title>{pageName}</Title>
    </>
  );
}
