import Head from 'next/head';
import { Typography } from 'antd';
import { ROUTES } from '../common/constants';
import { SignInContainer } from '../common/containers';

const { Title } = Typography;

export default function SignIn() {
  const pageName = ROUTES.SIGN_IN.NAME;

  return (
    <>
      <Head>
        <title>{pageName}</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <Title>{pageName}</Title>

      <SignInContainer />
    </>
  );
}
